name: CI
on: ["push"]
permissions:
  packages: write
  contents: write

jobs:
  build-x64:
    runs-on: ubuntu-latest
    container: alpine:3.22
    steps:
      - name: Install git
        run: |
          apk update
          apk add git

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install Dependencies
        run: |
          apk update
          apk add build-base cmake protobuf-dev vulkan-loader-dev glslang
          mkdir build && cd build
          cmake ../src
          cmake --build . -j$(nproc) 
          mv realesrgan-ncnn-vulkan realesrgan-ncnn-vulkan-alpine-x64
     
      - name: Upload x64 artifact
        uses: actions/upload-artifact@v4
        if: startsWith(github.ref, 'refs/tags/')
        with:
          retention-days: 1
          name: realesrgan-ncnn-vulkan-alpine-x64
          path: build/realesrgan-ncnn-vulkan-alpine-x64

  build-arm64:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Compile code in alpine:3.22 ARM64 container
        run: |
          docker run --rm --platform linux/arm64 \
          -v .:/source \
          alpine:3.22 /bin/sh -c "
            cd /source
            apk update
            apk add build-base cmake protobuf-dev vulkan-loader-dev glslang
            mkdir build && cd build
            cmake ../src
            cmake --build . -j$(nproc)
            mv realesrgan-ncnn-vulkan realesrgan-ncnn-vulkan-alpine-arm64
          "
      
      - name: Upload arm64 artifact
        uses: actions/upload-artifact@v4
        if: startsWith(github.ref, 'refs/tags/')
        with:
          retention-days: 1
          name: realesrgan-ncnn-vulkan-alpine-arm64
          path: build/realesrgan-ncnn-vulkan-alpine-arm64

  build-arm32:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Compile code in alpine:3.22 ARM32 container
        run: |
          docker run --rm --platform linux/arm/v7 \
          -v .:/source \
          alpine:3.22 /bin/sh -c "
            cd /source
            apk update
            apk add build-base cmake protobuf-dev vulkan-loader-dev glslang 
            mkdir build && cd build
            cmake ../src
            cmake --build . -j$(nproc)
            mv realesrgan-ncnn-vulkan realesrgan-ncnn-vulkan-alpine-arm32
          "
      
      - name: Upload arm32 artifact
        uses: actions/upload-artifact@v4
        if: startsWith(github.ref, 'refs/tags/')
        with:
          retention-days: 1
          name: realesrgan-ncnn-vulkan-alpine-arm32
          path: build/realesrgan-ncnn-vulkan-alpine-arm32

  create_release_upload:
    needs: [build-x64, build-arm64, build-arm32]
    runs-on: ubuntu-latest
    # CRITICAL: This condition ensures the job only runs if the push was a tag
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout To Create Release
        uses: actions/checkout@v4

      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts
      
      - name: List Downloaded Files
        run: |
          ls -lahR ./artifacts

      - name: Create Release
        # id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # tag_name: ${{ github.ref }}
          # name: Release ${{ github.ref }}
          draft: true
          files: |
            ./artifacts/realesrgan-ncnn-vulkan-alpine-arm64/realesrgan-ncnn-vulkan-alpine-arm64
            ./artifacts/realesrgan-ncnn-vulkan-alpine-x64/realesrgan-ncnn-vulkan-alpine-x64
            ./artifacts/realesrgan-ncnn-vulkan-alpine-arm32/realesrgan-ncnn-vulkan-alpine-arm32

