name: CI
on: ["push"]

jobs:
  build-x64:
    runs-on: ubuntu-latest
    container: alpine:3.22
    steps:
      - name: Install git
        run: |
          apk update
          apk add git

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install Dependencies
        run: |
          apk update
          apk add build-base cmake protobuf-dev vulkan-loader-dev glslang
          mkdir build && cd build
          cmake ../src
          cmake --build . -j$(nproc) 
     
      - name: Upload x64 artifact
        uses: actions/upload-artifact@v4
        if: startsWith(github.ref, 'refs/tags/')
        with:
          retention-days: 1
          name: realesrgan-ncnn-vulkan-x64
          path: build/realesrgan-ncnn-vulkan

  build-arm64:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Compile code in alpine:3.22 ARM64 container
        run: |
          docker run --rm --platform linux/arm64 \
          -v .:/source \
          alpine:3.22 /bin/sh -c "
            cd /source
            apk update
            apk add build-base cmake protobuf-dev vulkan-loader-dev glslang
            mkdir build && cd build
            cmake ../src
            cmake --build . -j$(nproc)
          "
      
      - name: Upload arm64 artifact
        uses: actions/upload-artifact@v4
        if: startsWith(github.ref, 'refs/tags/')
        with:
          retention-days: 1
          name: realesrgan-ncnn-vulkan-arm64
          path: build/realesrgan-ncnn-vulkan

  build-arm32:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Compile code in alpine:3.22 ARM32 container
        run: |
          docker run --rm --platform linux/arm/v7 \
          -v .:/source \
          alpine:3.22 /bin/sh -c "
            cd /source
            apk update
            apk add build-base cmake protobuf-dev vulkan-loader-dev glslang 
            mkdir build && cd build
            cmake ../src
            cmake --build . -j$(nproc)
          "
      
      - name: Upload arm32 artifact
        uses: actions/upload-artifact@v4
        if: startsWith(github.ref, 'refs/tags/')
        with:
          retention-days: 1
          name: realesrgan-ncnn-vulkan-arm32
          path: build/realesrgan-ncnn-vulkan

  create_release_upload:
    needs: [build-x64, build-arm64, build-arm32]
    runs-on: ubuntu-latest
    # CRITICAL: This condition ensures the job only runs if the push was a tag
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: .
          path: ./artifacts
      
      - name: List Downloaded Files
        run: ls -R ./artifacts

        # A. Create the GitHub Release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      # B. Upload ARM64 Asset
      - name: Upload ARM64 Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          # Path points to the file downloaded into the artifact directory
          asset_path: ./artifacts/realesrgan-ncnn-vulkan-arm64
          asset_name: realesrgan-ncnn-vulkan-alpine-arm64-${{ github.ref_name }}
          asset_content_type: application/octet-stream

      # C. Upload X64 Asset
      - name: Upload AMD64 Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/realesrgan-ncnn-vulkan-x64
          asset_name: realesrgan-ncnn-vulkan-alpine-x64-${{ github.ref_name }}
          asset_content_type: application/octet-stream

      # D. Upload ARM32 Asset
      - name: Upload AMD64 Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/realesrgan-ncnn-vulkan-arm32
          asset_name: realesrgan-ncnn-vulkan-alpine-arm32-${{ github.ref_name }}
          asset_content_type: application/octet-stream
